[application]
ios_info_plist = "./mobile/Info.plist"
android_manifest = "./mobile/AndroidManifest.xml"

[web.app]
title = "Terrier"

# include `assets` in web platform
[web.resource]
style = []
script = []

[web.resource.dev]
script = []
