[application]
asset_dir = "assets"
ios_info_plist = "./mobile/Info.plist"
android_manifest = "./mobile/AndroidManifest.xml"

[web.app]
title = "Terrier"
index = "./index.html"

[web.app.head]
html = """
<link rel="manifest" href="/api/manifest.json">
<meta name="theme-color" content="#ffffff">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
<link rel="apple-touch-icon" href="/icons/icon-192.png">
"""

# include `assets` in web platform
[web.resource]
style = []
script = []

[web.resource.dev]
script = []
