[project]
name = "terrier"
revision = "1.0"

[profiles.default]
OIDC_CLIENT_ID = { description = "Keycloak OIDC client ID" }
OIDC_CLIENT_SECRET = { description = "Keycloak OIDC client secret" }
KEYCLOAK_URL = { description = "Keycloak base URL" }
KEYCLOAK_REALM = { description = "Keycloak realm" }
OAUTH_RELAY_URL = { description = "OAuth relay callback URL" }

[profiles.dev]

[profiles.prod]
SENTRY_DSN = { description = "Sentry project DSN" }

[profiles.preview]
