//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "checkins")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub hacker_id: String,
    pub check_in_time: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::hacker::Entity",
        from = "Column::HackerId",
        to = "super::hacker::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Hacker,
}

impl Related<super::hacker::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Hacker.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
