//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "event")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub hackathon_id: Uuid,
    pub name: String,
    pub description: String,
    pub start_time: DateTime,
    pub end_time: DateTime,
    pub location: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::event_check_in::Entity")]
    EventCheckIn,
    #[sea_orm(
        belongs_to = "super::hackathon::Entity",
        from = "Column::HackathonId",
        to = "super::hackathon::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Hackathon,
    #[sea_orm(has_many = "super::project::Entity")]
    Project,
}

impl Related<super::event_check_in::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventCheckIn.def()
    }
}

impl Related<super::hackathon::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Hackathon.def()
    }
}

impl Related<super::project::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Project.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
