//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::HackathonRole;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "invitation")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub hackathon_id: Uuid,
    pub code: String,
    pub role: HackathonRole,
    pub target_email: Option<String>,
    pub is_used: bool,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::hackathon::Entity",
        from = "Column::HackathonId",
        to = "super::hackathon::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Hackathon,
}

impl Related<super::hackathon::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Hackathon.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
