//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub mod prelude;

pub mod applicant;
pub mod checkins;
pub mod evaluation;
pub mod events;
pub mod expo_evaluation;
pub mod hackathon;
pub mod hacker;
pub mod judge;
pub mod judge_assignment;
pub mod prize;
pub mod project;
pub mod sponsor;
pub mod sponsor_org;
pub mod submission;
pub mod team;
pub mod track;
pub mod user;
