//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub mod prelude;

pub mod application;
pub mod evaluation;
pub mod event;
pub mod event_check_in;
pub mod hackathon;
pub mod invitation;
pub mod judge_track_assign;
pub mod organizer;
pub mod prize_track;
pub mod project;
pub mod project_track_sub;
pub mod reimbursement_application;
pub mod sea_orm_active_enums;
pub mod sponsor;
pub mod sponsor_org;
pub mod team;
pub mod team_member;
pub mod user;
pub mod user_hackathon_role;
