//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::applicant::Entity as Applicant;
pub use super::checkins::Entity as Checkins;
pub use super::evaluation::Entity as Evaluation;
pub use super::events::Entity as Events;
pub use super::expo_evaluation::Entity as ExpoEvaluation;
pub use super::hackathon::Entity as Hackathon;
pub use super::hacker::Entity as Hacker;
pub use super::judge::Entity as Judge;
pub use super::judge_assignment::Entity as JudgeAssignment;
pub use super::prize::Entity as Prize;
pub use super::project::Entity as Project;
pub use super::sponsor::Entity as Sponsor;
pub use super::sponsor_org::Entity as SponsorOrg;
pub use super::submission::Entity as Submission;
pub use super::team::Entity as Team;
pub use super::track::Entity as Track;
pub use super::user::Entity as User;
