//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::JudgingMethod;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "prize_track")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub hackathon_id: Uuid,
    pub sponsor_org_id: Uuid,
    pub name: String,
    pub description: String,
    pub is_judging_started: bool,
    pub judging_method: JudgingMethod,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::evaluation::Entity")]
    Evaluation,
    #[sea_orm(
        belongs_to = "super::hackathon::Entity",
        from = "Column::HackathonId",
        to = "super::hackathon::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Hackathon,
    #[sea_orm(has_many = "super::judge_track_assign::Entity")]
    JudgeTrackAssign,
    #[sea_orm(has_many = "super::project_track_sub::Entity")]
    ProjectTrackSub,
    #[sea_orm(
        belongs_to = "super::sponsor_org::Entity",
        from = "Column::SponsorOrgId",
        to = "super::sponsor_org::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SponsorOrg,
}

impl Related<super::evaluation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Evaluation.def()
    }
}

impl Related<super::hackathon::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Hackathon.def()
    }
}

impl Related<super::judge_track_assign::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::JudgeTrackAssign.def()
    }
}

impl Related<super::project_track_sub::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectTrackSub.def()
    }
}

impl Related<super::sponsor_org::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SponsorOrg.def()
    }
}

impl Related<super::project::Entity> for Entity {
    fn to() -> RelationDef {
        super::project_track_sub::Relation::Project.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::project_track_sub::Relation::PrizeTrack.def().rev())
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        super::judge_track_assign::Relation::User.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::judge_track_assign::Relation::PrizeTrack.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
