//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "application_status")]
pub enum ApplicationStatus {
    #[sea_orm(string_value = "pending")]
    Pending,
    #[sea_orm(string_value = "accepted")]
    Accepted,
    #[sea_orm(string_value = "rejected")]
    Rejected,
    #[sea_orm(string_value = "waitlisted")]
    Waitlisted,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "evaluation_status")]
pub enum EvaluationStatus {
    #[sea_orm(string_value = "pending")]
    Pending,
    #[sea_orm(string_value = "complete")]
    Complete,
    #[sea_orm(string_value = "skipped")]
    Skipped,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "hackathon_role")]
pub enum HackathonRole {
    #[sea_orm(string_value = "hacker")]
    Hacker,
    #[sea_orm(string_value = "organizer")]
    Organizer,
    #[sea_orm(string_value = "judge")]
    Judge,
    #[sea_orm(string_value = "sponsor")]
    Sponsor,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "judging_method")]
pub enum JudgingMethod {
    #[sea_orm(string_value = "scoring")]
    Scoring,
    #[sea_orm(string_value = "expo")]
    Expo,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "reimbursement_status"
)]
pub enum ReimbursementStatus {
    #[sea_orm(string_value = "pending")]
    Pending,
    #[sea_orm(string_value = "approved")]
    Approved,
    #[sea_orm(string_value = "rejected")]
    Rejected,
    #[sea_orm(string_value = "paid")]
    Paid,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "team_member_status")]
pub enum TeamMemberStatus {
    #[sea_orm(string_value = "active")]
    Active,
    #[sea_orm(string_value = "invited")]
    Invited,
    #[sea_orm(string_value = "removed")]
    Removed,
}
