//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "sponsor_org")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    pub description: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::prize_track::Entity")]
    PrizeTrack,
    #[sea_orm(has_many = "super::sponsor::Entity")]
    Sponsor,
}

impl Related<super::prize_track::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PrizeTrack.def()
    }
}

impl Related<super::sponsor::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sponsor.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        super::sponsor::Relation::User.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::sponsor::Relation::SponsorOrg.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
