//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "sponsor_org")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    pub address: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::sponsor::Entity")]
    Sponsor,
}

impl Related<super::sponsor::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sponsor.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
