//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub username: String,
    pub password: String,
    pub role: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::applicant::Entity")]
    Applicant,
    #[sea_orm(has_many = "super::hacker::Entity")]
    Hacker,
    #[sea_orm(has_many = "super::judge::Entity")]
    Judge,
    #[sea_orm(has_many = "super::sponsor::Entity")]
    Sponsor,
}

impl Related<super::applicant::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Applicant.def()
    }
}

impl Related<super::hacker::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Hacker.def()
    }
}

impl Related<super::judge::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Judge.def()
    }
}

impl Related<super::sponsor::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sponsor.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
