//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub email: String,
    pub display_name: String,
    pub is_global_admin: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::application::Entity")]
    Application,
    #[sea_orm(has_many = "super::evaluation::Entity")]
    Evaluation,
    #[sea_orm(has_many = "super::judge_track_assign::Entity")]
    JudgeTrackAssign,
    #[sea_orm(has_many = "super::organizer::Entity")]
    Organizer,
    #[sea_orm(has_many = "super::sponsor::Entity")]
    Sponsor,
    #[sea_orm(has_many = "super::team_member::Entity")]
    TeamMember,
    #[sea_orm(has_many = "super::user_hackathon_role::Entity")]
    UserHackathonRole,
}

impl Related<super::application::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Application.def()
    }
}

impl Related<super::evaluation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Evaluation.def()
    }
}

impl Related<super::judge_track_assign::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::JudgeTrackAssign.def()
    }
}

impl Related<super::organizer::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizer.def()
    }
}

impl Related<super::sponsor::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sponsor.def()
    }
}

impl Related<super::team_member::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TeamMember.def()
    }
}

impl Related<super::user_hackathon_role::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserHackathonRole.def()
    }
}

impl Related<super::prize_track::Entity> for Entity {
    fn to() -> RelationDef {
        super::judge_track_assign::Relation::PrizeTrack.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::judge_track_assign::Relation::User.def().rev())
    }
}

impl Related<super::sponsor_org::Entity> for Entity {
    fn to() -> RelationDef {
        super::sponsor::Relation::SponsorOrg.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::sponsor::Relation::User.def().rev())
    }
}

impl Related<super::team::Entity> for Entity {
    fn to() -> RelationDef {
        super::team_member::Relation::Team.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::team_member::Relation::User.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
