//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

pub mod prelude;

pub mod applications;
pub mod event_checkins;
pub mod event_organizers;
pub mod events;
pub mod hackathons;
pub mod team_invitations;
pub mod team_join_requests;
pub mod teams;
pub mod user_hackathon_roles;
pub mod users;
