//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, utoipa :: ToSchema,
)]
#[sea_orm(table_name = "prize_track_entry")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub submission_id: i32,
    pub prize_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::prize::Entity",
        from = "Column::PrizeId",
        to = "super::prize::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Prize,
    #[sea_orm(
        belongs_to = "super::submission::Entity",
        from = "Column::SubmissionId",
        to = "super::submission::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Submission,
}

impl Related<super::prize::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Prize.def()
    }
}

impl Related<super::submission::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Submission.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
