//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, utoipa :: ToSchema,
)]
#[sea_orm(table_name = "teams")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub hackathon_id: i32,
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::hackathons::Entity",
        from = "Column::HackathonId",
        to = "super::hackathons::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Hackathons,
    #[sea_orm(has_many = "super::user_hackathon_roles::Entity")]
    UserHackathonRoles,
}

impl Related<super::hackathons::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Hackathons.def()
    }
}

impl Related<super::user_hackathon_roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserHackathonRoles.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
