/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/auth/login": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Initiate login flow */
		get: operations["login"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/auth/logout": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Log the current user out */
		get: operations["logout"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/auth/status": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get current user information */
		get: operations["status"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/hackathons": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Create a new hackathon */
		post: operations["create_hackathon"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/hackathons/public": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List all active hackathons */
		get: operations["list_public_hackathons"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/hackathons/{slug}/application": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get the current user's application for a hackathon */
		get: operations["get_application"];
		/** Save or update the current user's application (auto-save/draft) */
		put: operations["save_application"];
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/hackathons/{slug}/application/submit": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Submit the current user's application */
		post: operations["submit_application"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/hackathons/{slug}/application/upload-url": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Get a presigned URL for uploading a file */
		post: operations["get_upload_url"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/hackathons/{slug}/role": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get user's role for a specific hackathon */
		get: operations["get_user_role"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		ApplicationResponse: {
			/** Format: date-time */
			created_at: string;
			form_data: unknown;
			status: string;
			/** Format: date-time */
			submitted_at?: string | null;
			/** Format: date-time */
			updated_at: string;
		};
		CreateHackathonRequest: {
			description?: string | null;
			end_date: string;
			name: string;
			slug: string;
			start_date: string;
		};
		HackathonInfo: {
			description?: string | null;
			/** Format: date-time */
			end_date: string;
			/** Format: int32 */
			id: number;
			name: string;
			slug: string;
			/** Format: date-time */
			start_date: string;
		};
		LoginQuery: {
			redirect_uri?: string | null;
		};
		SaveApplicationRequest: {
			form_data: unknown;
		};
		SaveApplicationResponse: {
			status: string;
			success: boolean;
			/** Format: date-time */
			updated_at: string;
		};
		SubmitApplicationResponse: {
			/** Format: date-time */
			submitted_at: string;
			success: boolean;
		};
		UploadUrlRequest: {
			content_type: string;
			field_id: string;
			file_name: string;
		};
		UploadUrlResponse: {
			file_key: string;
			upload_url: string;
		};
		UserInfo: {
			email: string;
			id: string;
			is_admin: boolean;
			name?: string | null;
			picture?: string | null;
		};
		UserRoleResponse: {
			role: string;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	login: {
		parameters: {
			query?: {
				/** @description URI to redirect to after login */
				redirect_uri?: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Redirect to app after login */
			302: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	logout: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Redirect to logout */
			302: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	status: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description User information */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["UserInfo"];
				};
			};
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	create_hackathon: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CreateHackathonRequest"];
			};
		};
		responses: {
			/** @description Hackathon created successfully */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HackathonInfo"];
				};
			};
			/** @description Invalid request or slug already exists */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Not a global admin */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	list_public_hackathons: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description List of active hackathons */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HackathonInfo"][];
				};
			};
		};
	};
	get_application: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Hackathon slug */
				slug: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description User's application */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApplicationResponse"];
				};
			};
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description No access to this hackathon */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description No application found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	save_application: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Hackathon slug */
				slug: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["SaveApplicationRequest"];
			};
		};
		responses: {
			/** @description Application saved */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SaveApplicationResponse"];
				};
			};
			/** @description Cannot modify submitted application */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description No access to this hackathon */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	submit_application: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Hackathon slug */
				slug: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Application submitted */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SubmitApplicationResponse"];
				};
			};
			/** @description Application already submitted or no draft found */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description No access to this hackathon */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description No application found to submit */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	get_upload_url: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Hackathon slug */
				slug: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["UploadUrlRequest"];
			};
		};
		responses: {
			/** @description Presigned upload URL */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["UploadUrlResponse"];
				};
			};
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description No access to this hackathon */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Failed to generate upload URL */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	get_user_role: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Hackathon slug */
				slug: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description User's role in this hackathon */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["UserRoleResponse"];
				};
			};
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description No access to this hackathon */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Hackathon not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
}
