/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/auth/login": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Initiate login flow */
		get: operations["login"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/auth/logout": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Log the current user out */
		get: operations["logout"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/auth/status": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get current user information */
		get: operations["status"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/hackathons": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Create a new hackathon */
		post: operations["create_hackathon"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/hackathons/public": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List all active hackathons */
		get: operations["list_public_hackathons"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/hackathons/{slug}/application": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get the current user's application for a hackathon */
		get: operations["get_application"];
		/** Save or update the current user's application (auto-save/draft) */
		put: operations["save_application"];
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/hackathons/{slug}/application/submit": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Submit the current user's application */
		post: operations["submit_application"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/hackathons/{slug}/application/upload-url": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Get a presigned URL for uploading a file */
		post: operations["get_upload_url"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/hackathons/{slug}/role": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get user's role for a specific hackathon */
		get: operations["get_user_role"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/hackathons/{slug}/teams": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List all teams in a hackathon */
		get: operations["list_teams"];
		put?: never;
		/** Create a new team */
		post: operations["create_team"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/hackathons/{slug}/teams/invites/{invite_id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Respond to a team invite */
		post: operations["respond_to_invite"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/hackathons/{slug}/teams/my-team": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get current user's team and pending invites */
		get: operations["get_my_team"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/hackathons/{slug}/teams/search-participants": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Search participants to invite (those not in a team) */
		get: operations["search_participants"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/hackathons/{slug}/teams/{team_id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get a specific team's details */
		get: operations["get_team"];
		/** Update team details (leader only) */
		put: operations["update_team"];
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/hackathons/{slug}/teams/{team_id}/invite": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Invite a user to the team */
		post: operations["invite_member"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/hackathons/{slug}/teams/{team_id}/leave": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Leave a team */
		post: operations["leave_team"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/hackathons/{slug}/teams/{team_id}/request": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Request to join a team */
		post: operations["request_to_join"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/hackathons/{slug}/teams/{team_id}/requests": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get join requests for a team (leader only) */
		get: operations["get_join_requests"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/hackathons/{slug}/teams/{team_id}/requests/{request_id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Respond to a join request (leader only) */
		post: operations["respond_to_request"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		ApplicationResponse: {
			/** Format: date-time */
			created_at: string;
			form_data: unknown;
			status: string;
			/** Format: date-time */
			submitted_at?: string | null;
			/** Format: date-time */
			updated_at: string;
		};
		CreateHackathonRequest: {
			description?: string | null;
			end_date: string;
			name: string;
			slug: string;
			start_date: string;
		};
		CreateTeamRequest: {
			description?: string | null;
			name: string;
		};
		HackathonInfo: {
			description?: string | null;
			/** Format: date-time */
			end_date: string;
			/** Format: int32 */
			id: number;
			name: string;
			slug: string;
			/** Format: date-time */
			start_date: string;
		};
		InviteMemberRequest: {
			/** Format: int32 */
			user_id: number;
		};
		JoinRequestRequest: {
			message?: string | null;
		};
		JoinRequestResponse: {
			/** Format: date-time */
			created_at: string;
			/** Format: int32 */
			id: number;
			message?: string | null;
			status: string;
			user_email: string;
			/** Format: int32 */
			user_id: number;
			user_name: string;
		};
		LoginQuery: {
			redirect_uri?: string | null;
		};
		MyTeamResponse: {
			pending_invites: components["schemas"]["TeamInviteResponse"][];
			team?: null | components["schemas"]["TeamResponse"];
		};
		RespondToRequestRequest: {
			accept: boolean;
		};
		SaveApplicationRequest: {
			form_data: unknown;
		};
		SaveApplicationResponse: {
			status: string;
			success: boolean;
			/** Format: date-time */
			updated_at: string;
		};
		SubmitApplicationResponse: {
			/** Format: date-time */
			submitted_at: string;
			success: boolean;
		};
		TeamInviteResponse: {
			/** Format: date-time */
			created_at: string;
			/** Format: int32 */
			id: number;
			invited_by_name: string;
			status: string;
			/** Format: int32 */
			team_id: number;
			team_name: string;
		};
		TeamListItem: {
			description?: string | null;
			/** Format: int32 */
			id: number;
			/** Format: int32 */
			max_members: number;
			/** Format: int32 */
			member_count: number;
			name: string;
		};
		TeamMemberInfo: {
			email: string;
			/** Format: int32 */
			id: number;
			is_leader: boolean;
			name: string;
			/** Format: int32 */
			user_id: number;
		};
		TeamResponse: {
			/** Format: date-time */
			created_at: string;
			description?: string | null;
			/** Format: int32 */
			id: number;
			is_leader: boolean;
			is_member: boolean;
			/** Format: int32 */
			max_members: number;
			/** Format: int32 */
			member_count: number;
			members: components["schemas"]["TeamMemberInfo"][];
			name: string;
		};
		UpdateTeamRequest: {
			description?: string | null;
			name?: string | null;
		};
		UploadUrlRequest: {
			content_type: string;
			field_id: string;
			file_name: string;
		};
		UploadUrlResponse: {
			file_key: string;
			upload_url: string;
		};
		UserInfo: {
			email: string;
			id: string;
			is_admin: boolean;
			name?: string | null;
			picture?: string | null;
		};
		UserRoleResponse: {
			role: string;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	login: {
		parameters: {
			query?: {
				/** @description URI to redirect to after login */
				redirect_uri?: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Redirect to app after login */
			302: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	logout: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Redirect to logout */
			302: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	status: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description User information */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["UserInfo"];
				};
			};
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	create_hackathon: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CreateHackathonRequest"];
			};
		};
		responses: {
			/** @description Hackathon created successfully */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HackathonInfo"];
				};
			};
			/** @description Invalid request or slug already exists */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Not a global admin */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	list_public_hackathons: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description List of active hackathons */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HackathonInfo"][];
				};
			};
		};
	};
	get_application: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Hackathon slug */
				slug: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description User's application */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApplicationResponse"];
				};
			};
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description No access to this hackathon */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description No application found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	save_application: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Hackathon slug */
				slug: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["SaveApplicationRequest"];
			};
		};
		responses: {
			/** @description Application saved */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SaveApplicationResponse"];
				};
			};
			/** @description Cannot modify submitted application */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description No access to this hackathon */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	submit_application: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Hackathon slug */
				slug: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Application submitted */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SubmitApplicationResponse"];
				};
			};
			/** @description Application already submitted or no draft found */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description No access to this hackathon */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description No application found to submit */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	get_upload_url: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Hackathon slug */
				slug: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["UploadUrlRequest"];
			};
		};
		responses: {
			/** @description Presigned upload URL */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["UploadUrlResponse"];
				};
			};
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description No access to this hackathon */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Failed to generate upload URL */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	get_user_role: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Hackathon slug */
				slug: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description User's role in this hackathon */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["UserRoleResponse"];
				};
			};
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description No access to this hackathon */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Hackathon not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	list_teams: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Hackathon slug */
				slug: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description List of teams */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["TeamListItem"][];
				};
			};
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description No access to this hackathon */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	create_team: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Hackathon slug */
				slug: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CreateTeamRequest"];
			};
		};
		responses: {
			/** @description Team created */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["TeamResponse"];
				};
			};
			/** @description User already in a team */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description No access to this hackathon */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	respond_to_invite: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Hackathon slug */
				slug: string;
				/** @description Invite ID */
				invite_id: number;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["RespondToRequestRequest"];
			};
		};
		responses: {
			/** @description Response recorded */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Already in a team or team full */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Invite not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	get_my_team: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Hackathon slug */
				slug: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description User's team info */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["MyTeamResponse"];
				};
			};
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description No access to this hackathon */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	search_participants: {
		parameters: {
			query: {
				/** @description Search query */
				q: string;
			};
			header?: never;
			path: {
				/** @description Hackathon slug */
				slug: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description List of participants */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["TeamMemberInfo"][];
				};
			};
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	get_team: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Hackathon slug */
				slug: string;
				/** @description Team ID */
				team_id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Team details */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["TeamResponse"];
				};
			};
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description No access to this hackathon */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Team not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	update_team: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Hackathon slug */
				slug: string;
				/** @description Team ID */
				team_id: number;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["UpdateTeamRequest"];
			};
		};
		responses: {
			/** @description Team updated */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["TeamResponse"];
				};
			};
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Not team leader */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Team not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	invite_member: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Hackathon slug */
				slug: string;
				/** @description Team ID */
				team_id: number;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["InviteMemberRequest"];
			};
		};
		responses: {
			/** @description Invite sent */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description User already in a team or team full */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Not team member */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description User not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	leave_team: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Hackathon slug */
				slug: string;
				/** @description Team ID */
				team_id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Left team */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Cannot leave as only leader */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Not a member */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Team not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	request_to_join: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Hackathon slug */
				slug: string;
				/** @description Team ID */
				team_id: number;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["JoinRequestRequest"];
			};
		};
		responses: {
			/** @description Request sent */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Already in a team or team full */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Team not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	get_join_requests: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Hackathon slug */
				slug: string;
				/** @description Team ID */
				team_id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description List of join requests */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["JoinRequestResponse"][];
				};
			};
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Not team leader */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	respond_to_request: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Hackathon slug */
				slug: string;
				/** @description Team ID */
				team_id: number;
				/** @description Request ID */
				request_id: number;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["RespondToRequestRequest"];
			};
		};
		responses: {
			/** @description Response recorded */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Team is full */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Not team leader */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Request not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
}
