use super::application_form::FieldCondition;
use super::application_form::*;

/// Create the TartanHacks application form preset
pub fn tartanhacks_preset() -> FormSchema {
    let mut order = 0;
    let mut next_order = || {
        let o = order;
        order += 1;
        o
    };

    FormSchema {
        title: "TartanHacks Application".to_string(),
        description: Some("Apply to participate in TartanHacks".to_string()),
        fields: vec![
            // Basic Information
            FormField {
                id: "first_name".to_string(),
                field_type: FieldType::Text,
                label: "First Name".to_string(),
                name: "first_name".to_string(),
                placeholder: None,
                required: true,
                help_text: None,
                default_value: None,
                options: None,
                validation: None,
                order: next_order(),
                conditional: None,
                file_path: None,
            },
            FormField {
                id: "middle_name".to_string(),
                field_type: FieldType::Text,
                label: "Middle Name".to_string(),
                name: "middle_name".to_string(),
                placeholder: None,
                required: false,
                help_text: None,
                default_value: None,
                options: None,
                validation: None,
                order: next_order(),
                conditional: None,
                file_path: None,
            },
            FormField {
                id: "last_name".to_string(),
                field_type: FieldType::Text,
                label: "Last Name".to_string(),
                name: "last_name".to_string(),
                placeholder: None,
                required: true,
                help_text: None,
                default_value: None,
                options: None,
                validation: None,
                order: next_order(),
                conditional: None,
                file_path: None,
            },
            FormField {
                id: "age".to_string(),
                field_type: FieldType::Number,
                label: "Age".to_string(),
                name: "age".to_string(),
                placeholder: None,
                required: true,
                help_text: None,
                default_value: None,
                options: None,
                validation: Some(FieldValidation::Number(NumberValidation {
                    min: Some(13.0),
                    max: Some(120.0),
                    step: Some(1.0),
                })),
                order: next_order(),
                conditional: None,
                file_path: None,
            },
            // Gender
            FormField {
                id: "gender".to_string(),
                field_type: FieldType::Radio,
                label: "What is your gender?".to_string(),
                name: "gender".to_string(),
                placeholder: None,
                required: true,
                help_text: None,
                default_value: None,
                options: Some(vec![
                    SelectOption {
                        label: "Woman".to_string(),
                        value: "woman".to_string(),
                    },
                    SelectOption {
                        label: "Man".to_string(),
                        value: "man".to_string(),
                    },
                    SelectOption {
                        label: "Non-binary".to_string(),
                        value: "non_binary".to_string(),
                    },
                    SelectOption {
                        label: "Prefer to self-describe".to_string(),
                        value: "self_describe".to_string(),
                    },
                    SelectOption {
                        label: "Prefer not to say".to_string(),
                        value: "prefer_not_to_say".to_string(),
                    },
                ]),
                validation: None,
                order: next_order(),
                conditional: None,
                file_path: None,
            },
            FormField {
                id: "gender_self_describe".to_string(),
                field_type: FieldType::Text,
                label: "If you prefer to self-describe, please specify".to_string(),
                name: "gender_self_describe".to_string(),
                placeholder: None,
                required: false,
                help_text: None,
                default_value: None,
                options: None,
                validation: None,
                order: next_order(),
                conditional: Some(FieldCondition {
                    field: "gender".to_string(),
                    value: vec!["self_describe".to_string()],
                }),
                file_path: None,
            },
            FormField {
                id: "transgender".to_string(),
                field_type: FieldType::Radio,
                label: "Do you identify as transgender?".to_string(),
                name: "transgender".to_string(),
                placeholder: None,
                required: true,
                help_text: None,
                default_value: None,
                options: Some(vec![
                    SelectOption {
                        label: "Yes".to_string(),
                        value: "yes".to_string(),
                    },
                    SelectOption {
                        label: "No".to_string(),
                        value: "no".to_string(),
                    },
                    SelectOption {
                        label: "Prefer not to say".to_string(),
                        value: "prefer_not_to_say".to_string(),
                    },
                ]),
                validation: None,
                order: next_order(),
                conditional: None,
                file_path: None,
            },
            // Race and Ethnicity
            FormField {
                id: "race_ethnicity".to_string(),
                field_type: FieldType::CheckboxGroup,
                label: "Please select your race/ethnicity (select all that apply)".to_string(),
                name: "race_ethnicity".to_string(),
                placeholder: None,
                required: true,
                help_text: None,
                default_value: None,
                options: Some(vec![
                    SelectOption {
                        label: "Black / African American (including Sub-Saharan African diaspora)"
                            .to_string(),
                        value: "black".to_string(),
                    },
                    SelectOption {
                        label: "Middle Eastern / North African (e.g., Egyptian, Lebanese, Iranian)"
                            .to_string(),
                        value: "middle_eastern".to_string(),
                    },
                    SelectOption {
                        label: "East Asian (e.g., Chinese, Korean, Japanese)".to_string(),
                        value: "east_asian".to_string(),
                    },
                    SelectOption {
                        label: "South Asian (e.g., Indian, Pakistani, Bangladeshi)".to_string(),
                        value: "south_asian".to_string(),
                    },
                    SelectOption {
                        label: "Southeast Asian (e.g. Filipino, Vietnamese, Thai, Indonesian)"
                            .to_string(),
                        value: "southeast_asian".to_string(),
                    },
                    SelectOption {
                        label: "Hispanic / Latine".to_string(),
                        value: "hispanic".to_string(),
                    },
                    SelectOption {
                        label: "Native American / Alaska Native".to_string(),
                        value: "native_american".to_string(),
                    },
                    SelectOption {
                        label: "Pacific Islander / Native Hawaiian".to_string(),
                        value: "pacific_islander".to_string(),
                    },
                    SelectOption {
                        label: "White / European".to_string(),
                        value: "white".to_string(),
                    },
                    SelectOption {
                        label: "Prefer to self-describe".to_string(),
                        value: "self_describe".to_string(),
                    },
                    SelectOption {
                        label: "Prefer not to say".to_string(),
                        value: "prefer_not_to_say".to_string(),
                    },
                ]),
                validation: None,
                order: next_order(),
                conditional: None,
                file_path: None,
            },
            FormField {
                id: "race_self_describe_text".to_string(),
                field_type: FieldType::Text,
                label: "If you prefer to self-describe, please specify".to_string(),
                name: "race_self_describe_text".to_string(),
                placeholder: None,
                required: false,
                help_text: None,
                default_value: None,
                options: None,
                validation: None,
                order: next_order(),
                conditional: Some(FieldCondition {
                    field: "race_ethnicity".to_string(),
                    value: vec!["self_describe".to_string()],
                }),
                file_path: None,
            },
            // Region
            FormField {
                id: "state".to_string(),
                field_type: FieldType::Text,
                label: "State".to_string(),
                name: "state".to_string(),
                placeholder: None,
                required: false,
                help_text: None,
                default_value: None,
                options: None,
                validation: None,
                order: next_order(),
                conditional: None,
                file_path: None,
            },
            FormField {
                id: "country".to_string(),
                field_type: FieldType::Text,
                label: "Country".to_string(),
                name: "country".to_string(),
                placeholder: None,
                required: true,
                help_text: None,
                default_value: None,
                options: None,
                validation: None,
                order: next_order(),
                conditional: None,
                file_path: None,
            },
            // Academic
            FormField {
                id: "school".to_string(),
                field_type: FieldType::Text,
                label: "School".to_string(),
                name: "school".to_string(),
                placeholder: None,
                required: true,
                help_text: None,
                default_value: None,
                options: None,
                validation: None,
                order: next_order(),
                conditional: None,
                file_path: None,
            },
            FormField {
                id: "college".to_string(),
                field_type: FieldType::Select,
                label: "College (if CMU)".to_string(),
                name: "college".to_string(),
                placeholder: Some("Select your college".to_string()),
                required: false,
                help_text: None,
                default_value: None,
                options: Some(vec![
                    SelectOption {
                        label: "School of Computer Science".to_string(),
                        value: "scs".to_string(),
                    },
                    SelectOption {
                        label: "Carnegie Institute of Technology".to_string(),
                        value: "cit".to_string(),
                    },
                    SelectOption {
                        label: "College of Fine Arts".to_string(),
                        value: "cfa".to_string(),
                    },
                    SelectOption {
                        label: "Dietrich College of Humanities and Social Sciences".to_string(),
                        value: "dietrich".to_string(),
                    },
                    SelectOption {
                        label: "Mellon College of Science".to_string(),
                        value: "mcs".to_string(),
                    },
                    SelectOption {
                        label: "Tepper School of Business".to_string(),
                        value: "tepper".to_string(),
                    },
                    SelectOption {
                        label: "Heinz College".to_string(),
                        value: "heinz".to_string(),
                    },
                ]),
                validation: None,
                order: next_order(),
                conditional: None,
                file_path: None,
            },
            FormField {
                id: "academic_program".to_string(),
                field_type: FieldType::Select,
                label: "Academic Program".to_string(),
                name: "academic_program".to_string(),
                placeholder: Some("Select your program".to_string()),
                required: true,
                help_text: None,
                default_value: None,
                options: Some(vec![
                    SelectOption {
                        label: "Undergraduate".to_string(),
                        value: "undergrad".to_string(),
                    },
                    SelectOption {
                        label: "Masters".to_string(),
                        value: "masters".to_string(),
                    },
                    SelectOption {
                        label: "Doctorate".to_string(),
                        value: "doctorate".to_string(),
                    },
                    SelectOption {
                        label: "Other".to_string(),
                        value: "other".to_string(),
                    },
                ]),
                validation: None,
                order: next_order(),
                conditional: None,
                file_path: None,
            },
            FormField {
                id: "academic_program_other".to_string(),
                field_type: FieldType::Text,
                label: "If other, please specify".to_string(),
                name: "academic_program_other".to_string(),
                placeholder: None,
                required: false,
                help_text: None,
                default_value: None,
                options: None,
                validation: None,
                order: next_order(),
                conditional: Some(FieldCondition {
                    field: "academic_program".to_string(),
                    value: vec!["other".to_string()],
                }),
                file_path: None,
            },
            FormField {
                id: "graduation_year".to_string(),
                field_type: FieldType::Select,
                label: "Graduation Year".to_string(),
                name: "graduation_year".to_string(),
                placeholder: Some("Select your graduation year".to_string()),
                required: true,
                help_text: None,
                default_value: None,
                options: Some(vec![
                    SelectOption {
                        label: "2026".to_string(),
                        value: "2026".to_string(),
                    },
                    SelectOption {
                        label: "2027".to_string(),
                        value: "2027".to_string(),
                    },
                    SelectOption {
                        label: "2028".to_string(),
                        value: "2028".to_string(),
                    },
                    SelectOption {
                        label: "2029".to_string(),
                        value: "2029".to_string(),
                    },
                    SelectOption {
                        label: "2030".to_string(),
                        value: "2030".to_string(),
                    },
                ]),
                validation: None,
                order: next_order(),
                conditional: None,
                file_path: None,
            },
            FormField {
                id: "major".to_string(),
                field_type: FieldType::Text,
                label: "Major".to_string(),
                name: "major".to_string(),
                placeholder: None,
                required: true,
                help_text: None,
                default_value: None,
                options: None,
                validation: None,
                order: next_order(),
                conditional: None,
                file_path: None,
            },
            // Hackathon-related
            FormField {
                id: "hackathon_experience".to_string(),
                field_type: FieldType::Select,
                label: "Years of hackathon experience".to_string(),
                name: "hackathon_experience".to_string(),
                placeholder: Some("Select your experience level".to_string()),
                required: true,
                help_text: None,
                default_value: None,
                options: Some(vec![
                    SelectOption {
                        label: "0".to_string(),
                        value: "0".to_string(),
                    },
                    SelectOption {
                        label: "1-3".to_string(),
                        value: "1-3".to_string(),
                    },
                    SelectOption {
                        label: "4+".to_string(),
                        value: "4+".to_string(),
                    },
                ]),
                validation: None,
                order: next_order(),
                conditional: None,
                file_path: None,
            },
            FormField {
                id: "resume".to_string(),
                field_type: FieldType::File,
                label: "Resume".to_string(),
                name: "resume".to_string(),
                placeholder: None,
                required: true,
                help_text: None,
                default_value: None,
                options: None,
                validation: Some(FieldValidation::File(FileValidation {
                    accept: Some(".pdf,.doc,.docx".to_string()),
                    max_size: Some(5 * 1024 * 1024), // 5MB
                    multiple: false,
                })),
                order: next_order(),
                conditional: None,
                file_path: Some("applications/{hackathon_id}/{user_id}/resume".to_string()),
            },
            FormField {
                id: "github_url".to_string(),
                field_type: FieldType::Url,
                label: "GitHub/GitLab/etc. profile URL".to_string(),
                name: "github_url".to_string(),
                placeholder: Some("https://github.com/username".to_string()),
                required: true,
                help_text: None,
                default_value: None,
                options: None,
                validation: None,
                order: next_order(),
                conditional: None,
                file_path: None,
            },
            FormField {
                id: "linkedin_url".to_string(),
                field_type: FieldType::Url,
                label: "LinkedIn profile URL".to_string(),
                name: "linkedin_url".to_string(),
                placeholder: Some("https://linkedin.com/in/username".to_string()),
                required: false,
                help_text: None,
                default_value: None,
                options: None,
                validation: None,
                order: next_order(),
                conditional: None,
                file_path: None,
            },
            FormField {
                id: "website".to_string(),
                field_type: FieldType::Url,
                label: "Website".to_string(),
                name: "website".to_string(),
                placeholder: Some("https://example.com".to_string()),
                required: false,
                help_text: None,
                default_value: None,
                options: None,
                validation: None,
                order: next_order(),
                conditional: None,
                file_path: None,
            },
            FormField {
                id: "design_portfolio".to_string(),
                field_type: FieldType::Url,
                label: "Design portfolio".to_string(),
                name: "design_portfolio".to_string(),
                placeholder: Some("https://behance.net/username".to_string()),
                required: false,
                help_text: None,
                default_value: None,
                options: None,
                validation: None,
                order: next_order(),
                conditional: None,
                file_path: None,
            },
            // Diversity statement
            FormField {
                id: "diversity_statement".to_string(),
                field_type: FieldType::Textarea,
                label: "Statement of diversity".to_string(),
                name: "diversity_statement".to_string(),
                placeholder: None,
                required: false,
                help_text: None,
                default_value: None,
                options: None,
                validation: None,
                order: next_order(),
                conditional: None,
                file_path: None,
            },
            // Logistics
            FormField {
                id: "phone".to_string(),
                field_type: FieldType::Tel,
                label: "Phone number".to_string(),
                name: "phone".to_string(),
                placeholder: None,
                required: true,
                help_text: None,
                default_value: None,
                options: None,
                validation: None,
                order: next_order(),
                conditional: None,
                file_path: None,
            },
            FormField {
                id: "dietary_restrictions".to_string(),
                field_type: FieldType::Text,
                label: "Dietary restrictions".to_string(),
                name: "dietary_restrictions".to_string(),
                placeholder: None,
                required: false,
                help_text: None,
                default_value: None,
                options: None,
                validation: None,
                order: next_order(),
                conditional: None,
                file_path: None,
            },
            FormField {
                id: "shirt_size".to_string(),
                field_type: FieldType::Select,
                label: "Short size".to_string(),
                name: "shirt_size".to_string(),
                placeholder: Some("Select your size".to_string()),
                required: true,
                help_text: None,
                default_value: None,
                options: Some(vec![
                    SelectOption {
                        label: "XS".to_string(),
                        value: "xs".to_string(),
                    },
                    SelectOption {
                        label: "S".to_string(),
                        value: "s".to_string(),
                    },
                    SelectOption {
                        label: "M".to_string(),
                        value: "m".to_string(),
                    },
                    SelectOption {
                        label: "L".to_string(),
                        value: "l".to_string(),
                    },
                    SelectOption {
                        label: "XL".to_string(),
                        value: "xl".to_string(),
                    },
                    SelectOption {
                        label: "XXL".to_string(),
                        value: "xxl".to_string(),
                    },
                ]),
                validation: None,
                order: next_order(),
                conditional: None,
                file_path: None,
            },
            FormField {
                id: "will_use_hardware".to_string(),
                field_type: FieldType::Checkbox,
                label: "Will you use hardware?".to_string(),
                name: "will_use_hardware".to_string(),
                placeholder: None,
                required: false,
                help_text: None,
                default_value: None,
                options: None,
                validation: None,
                order: next_order(),
                conditional: None,
                file_path: None,
            },
            FormField {
                id: "additional_notes".to_string(),
                field_type: FieldType::Textarea,
                label: "Additional notes".to_string(),
                name: "additional_notes".to_string(),
                placeholder: None,
                required: false,
                help_text: None,
                default_value: None,
                options: None,
                validation: None,
                order: next_order(),
                conditional: None,
                file_path: None,
            },
            // Consent
            FormField {
                id: "code_of_conduct".to_string(),
                field_type: FieldType::Radio,
                label: "THX Code of Conduct".to_string(),
                name: "code_of_conduct".to_string(),
                placeholder: None,
                required: true,
                help_text: None,
                default_value: None,
                options: Some(vec![SelectOption {
                    label: "I agree to abide by the TartanHacks Code of Conduct".to_string(),
                    value: "agree".to_string(),
                }]),
                validation: None,
                order: next_order(),
                conditional: None,
                file_path: None,
            },
            FormField {
                id: "media_release".to_string(),
                field_type: FieldType::Radio,
                label: "Media release".to_string(),
                name: "media_release".to_string(),
                placeholder: None,
                required: true,
                help_text: None,
                default_value: None,
                options: Some(vec![SelectOption {
                    label: "I consent to being photographed/recorded at TartanHacks".to_string(),
                    value: "agree".to_string(),
                }]),
                validation: None,
                order: next_order(),
                conditional: None,
                file_path: None,
            },
            FormField {
                id: "sponsor_info".to_string(),
                field_type: FieldType::Checkbox,
                label: "Authorize to send info to sponsors".to_string(),
                name: "sponsor_info".to_string(),
                placeholder: None,
                required: false,
                help_text: None,
                default_value: Some("true".to_string()),
                options: None,
                validation: None,
                order: next_order(),
                conditional: None,
                file_path: None,
            },
            FormField {
                id: "signature".to_string(),
                field_type: FieldType::Text,
                label: "Signature".to_string(),
                name: "signature".to_string(),
                placeholder: Some("Type your full name".to_string()),
                required: true,
                help_text: None,
                default_value: None,
                options: None,
                validation: None,
                order: next_order(),
                conditional: None,
                file_path: None,
            },
            FormField {
                id: "signature_date".to_string(),
                field_type: FieldType::Date,
                label: "Date".to_string(),
                name: "signature_date".to_string(),
                placeholder: None,
                required: true,
                help_text: None,
                default_value: None,
                options: None,
                validation: None,
                order: next_order(),
                conditional: None,
                file_path: None,
            },
        ],
        version: "1.0".to_string(),
    }
}
